### ISSUE TITLE
Problems with some TimeZones starting with 2.10

### ISSUE THREAD

**Issue by maros** [houseabsolute/DateTime-TimeZone#18]
In the DateTime::Format::CLDR testsuite I noticed that the name of some timezones changed starting with 2.10

See the difference between
https://metacpan.org/source/DROLSKY/DateTime-TimeZone-2.09/lib/DateTime/TimeZone/America/Argentina/Buenos_Aires.pm
https://metacpan.org/source/DROLSKY/DateTime-TimeZone-2.10/lib/DateTime/TimeZone/America/Argentina/Buenos_Aires.pm

Afaict ART is the correct name for this timezone. This issue also seems to affect other timezones such as Asia/Kabul and possibly others.

**Comment by autarch** [comment]
This was a change made in the official IANA time zone database sources. See https://github.com/eggert/tz/blob/master/southamerica#L401

The short names are entirely arbitrary things that the time zone database maintainers made up, and they can change them as they see fit.

**Comment by arodland** [comment]
More specifically, https://github.com/eggert/tz/blob/c9e6ef07cc6f1062ddd032c96c5172f403c0058f/NEWS#L14-L35
