### ISSUE TITLE
Misindexing on MetaCPAN

### ISSUE THREAD

**Issue by oschwald** [houseabsolute/DateTime-TimeZone#19]
The `DateTime::TimeZone::Catalog` link points to https://metacpan.org/pod/distribution/DateTime-TimeZone/tools/parse_olson, which has messed up pod. I was going to open an issue on MetaCPAN, but looking at that script, it appears there is a (non-functional?) hack to fix an issue like this.

**Comment by autarch** [comment]
Sheesh, I wonder if metacpan got more clever or something. This used to work, I think. I'll fix it again.

**Comment by autarch** [comment]
Argh, thought I fixed it in 2.12 but apparently not. No idea why.

**Comment by autarch** [comment]
Finally fixed for real in 2.13
