### ISSUE TITLE
Recommended way to load all timezone files?

### ISSUE THREAD

**Issue by oschwald** [houseabsolute/DateTime-TimeZone#20]
Our app receives timezones as part of user input and potentially could use any of the timezone modules. The docs [recommend preloading the modules](https://metacpan.org/pod/distribution/DateTime-TimeZone/tools/parse_olson) when using a pre-forking system. Is there a convenient way to preload _all_ of the timezone modules?

**Comment by autarch** [comment]
Something like this should work ...

```perl
DateTime::TimeZone->new( name => $_ ) for DateTime::TimeZone->all_names
```

That will use a fair bit of memory though.

**Comment by oschwald** [comment]
Thanks!
