### ISSUE TITLE
CONTRIBUTING.md refers to non-existent Makefile.PL and Build.PL

### ISSUE THREAD

**Issue by jkeenan** [houseabsolute/DateTime-TimeZone#27]
File ```CONTRIBUTING.md``` states:
```
The distribution is managed with
[Dist::Zilla](https://metacpan.org/release/Dist-Zilla).

However, you can still compile and test the code with the `Makefile.PL` or
`Build.PL` in the repository:

    perl Makefile.PL
    make
    make test

or
    perl Build.PL
    ./Build
    ./Build test
```
However, there is no ```Makefile.PL``` or ```Build.PL``` in the repository.
```
[DateTime-TimeZone] 519 $ !512
find . -type f -iname '*.Pl'
./t/check_datetime_version.pl
```
How am I to proceed?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
I would like to suggest one reason why the DateTime-TimeZone repository ought to contain a ```Makefile.PL```: circular dependencies.

This repository is currently managed by Dist-Zilla.  https://metacpan.org/pod/Dist::Zilla clearly shows that it has a dependency on DateTime.  https://metacpan.org/pod/DateTime, in turn, shows that DateTime has a dependency on DateTime::TimeZone.

(Granted, this situation is aggravated by the fact that https://github.com/rjbs/Dist-Zilla is **itself** managed by Dist::Zilla and lacks either a ```Makefile.PL``` or a ```Build.PL`` -- which means that either you already have to have DZ installed to work on DZ or you have to copy a ```Makefile.PL`` into your checkout from the CPAN distribution of Dist-Zilla.)

IMO, every library for which DZ is a reverse dependency ought to include a ```Makefile.PL``` in its repository.  That way, any Perl user anywhere can use ExtUtils::MakeMaker to work on such a library whether or not DZ has been (successfully) installed.

Thank you very much.
Jim Keenan

**Comment by autarch** [comment]
All of my modules that use dzil should have a Makefile.PL or Build.PL in the repo. The fact that this didn't was an oversight. I checked it in and it will be updated after each release going forward.
