### ISSUE TITLE
Daylight Saving Time change in Brazil

### ISSUE THREAD

**Issue by richieri** [houseabsolute/DateTime-TimeZone#31]
Dear friends,

I'm not sure if this is an "issue" that concerns to DateTime perl module. The government in Brazil (America/Sao_Paulo and others) has change the day which we will enter in Dayligh Saving Time period, which should be at October 21, but was changed to November 18h.

How should I proceed to ask the adjustments in the module or, should I look after other place, like linux kernel or something like that?

Thanks!

**Comment by autarch** [comment]
Thanks for the info.

The time zone info in DateTime::TimeZone is generated from the IANA time zone database. Whenever that's updated we regenerate that distro, so there's nothing you need to do to make this happen.
