### ISSUE TITLE
Doc glitch re "floating" time zone

### ISSUE THREAD

**Issue by jimav** [houseabsolute/DateTime-TimeZone#35]
There's a documentation glitch where DateTime::TimeZone says

  "A floating time zone does have any offset, and is always the same time."

Probably that was meant to say "A floating time zone does NOT ...", consistent with DateTime::TimeZone::Floating (which says "A floating time zone does hot have I<any> offset...").

Patch attached.
[patch1.txt](https://github.com/houseabsolute/DateTime-TimeZone/files/2743138/patch1.txt)

**Comment by autarch** [comment]
Thanks, but I think you must've been looking at an old version. I fixed this a few releases ago.
