### ISSUE TITLE
'uk' is not a valid alpha-2 country code

### ISSUE THREAD

**Issue by ggl** [houseabsolute/DateTime-TimeZone#39]
DateTime::TimeZone->countries return 'uk' among the countries.

Locale::Codes->code2name returns the following warning when attempting to convert 'uk' to a country name:

ERROR: _code: code not in codeset: uk [alpha-2]

**Comment by autarch** [comment]
Someone asked for `uk` to be added as an alias for `gb` many years ago, and I can't remember why. I don't want to remove it now, since that would break backwards incompatibility. I added something to the docs about this.
