### ISSUE TITLE
GMT offsets +/- 12

### ISSUE THREAD

**Issue by rcm4717211** [houseabsolute/DateTime-TimeZone#40]
Can you please add all the Etc/GMT offsets:
GMT   GMT-0  GMT-1  GMT-10  GMT-11  GMT-12  GMT-13  GMT-2  GMT-3  GMT-4  GMT-5  GMT-6  GMT-7  GMT-8  GMT-9
GMT0  GMT+0  GMT+1  GMT+10  GMT+11  GMT+12  GMT-14  GMT+2  GMT+3  GMT+4  GMT+5  GMT+6  GMT+7  GMT+8  GMT+9

**Comment by autarch** [comment]
This was already done in 2.38.
