### ISSUE TITLE
2.40 seems to be missing a lot of data

### ISSUE THREAD

**Issue by pghmcfc** [houseabsolute/DateTime-TimeZone#43]
The tarball for 2.40 is about 10% the size of the tarball for 2.39. In addition to lots of missing data, the DT::TZ::Catalog module seems to be missing too, which led to a failure to install due to missing dependency on that when I tried to install a locally packaged 2.40 as an RPM. Conversion script gone wrong?

**Comment by autarch** [comment]
Oops, I made a mess. I will release a 2.41 that fixes this in a few minutes. Thanks for the heads up!

**Comment by autarch** [comment]
Fixed in v2.41.
