### ISSUE TITLE
Leftover file `#dist.ini#` in 2.44

### ISSUE THREAD

**Issue by perlpunk** [houseabsolute/DateTime-TimeZone#46]
I found this `#dist.ini#` file while maintaining the perl repository in Suse Open Build Service: https://metacpan.org/source/DROLSKY/DateTime-TimeZone-2.44
Also files like `azure-pipelines.yml` could probably be excluded from the tarball.

**Comment by autarch** [comment]
The `#dist.ini#` will be fixed in the next release. But I don't see a good reason to exclude CI config files. It's not going to cause any problems to have it included, and someone may find it interesting.

**Comment by autarch** [comment]
Fixed in v2.45.
